name: IGPrison
version: 1.0.0
description: Ignition Gaming Prison
author: [BuffsOverNexus, LegendForHire]
main: us.ignitiongaming.IGPrison
depend: [Vault]

commands:
     iga:
        description: Access the administrative commands of Ignition Gaming.
        permission: igprison.iga
     ighelp:
        description: Spawn a book that describes the server.
        permission: igprison.ighelp
     rankup:
        description: Rankup to the next level if you're still within the prison!
        permission: igprison.rankup
     donate:
        description: View the link to donate to our server!
        permission: igprison.donate
     points:
        description: View your donation point count.
        permission: igprison.donatorpoints
     donatorpoints:
        description: View your donation point count.
        permission: igprison.donatorpoints
     solitary:
        description: Add or remove a player from solitary confinement.
        permission: igprison.solitarycmd
     spawn:
        description: Go to spawn based on your rank.
        permission: igprison.spawn
     setspawn:
        description: Set the spawn of a location.
        permission: igprison.setspawn
     warp:
        description: Warp to a location.
        permission: igprison.warp
     now:
        description: The current time based on the server.
        permission: igprison.now
     smelt:
        description: Smell all of the ore in your inventory.
        permission: igprison.smelt
     sc:
        description: Shortcut for staffchat.
        permission: igprison.staffchat
     staffchat:
        description: Toggles staffchat or sends one message to staffchat.
        permission: igprison.staffchat
     lockdown:
        description: Access the lockdown feature of prison.
        permission: igprison.lockdown
     setrank:
        description: Set the rank of a user.
        permission: igprison.setrank
     igdev:
        description: Development commands for IG.
        permission: igprison.igdev
     goto:
        description: Go to a player!
        permission: igprison.goto
     bring:
        description: Bring player(s) to you!
        permission: igprison.bring
     igkick:
        description: Kicks a player
        permission: igprison.kick
     igban:
        description: Bans a player
        permission: igprison.ban
     clearchat:
        description: Clears chat for all players
        permission: igprison.clearchat
     nickname:
        description: Sets your nickname
        permission: igprison.nickname
     whois:
        description: Gets a player with a nickname's real name
        permission: igprison.whois
     link:
        description: Link your Ignition Gaming account to your Minecraft account.
        permission: igprison.link
     gang:
        description: Ignition Gaming's gang system.
        permission: igprison.gang
     guard:
        description: Activate your guard status and patrol the jail.
        permission: igprison.guardcmd
     warden:
        description: Activate your warden status and patrol the jail.
        permission: igprison.wardencmd
     bounty:
        description: Ignition Gaming's Prison bounty system.
        permission: igprison.bounty
     tower:
        description: Teleport to a Guard tower.
        permission: igprison.tower
