name: IGPrison
version: 0.1.0
description: Ignition Gaming Prison
author: [BuffsOverNexus, LegendForHire]
main: us.ignitiongaming.IGPrison
depends: [Vault]

commands:
     iga:
        description: Access the administrative commands of Ignition Gaming.
     ighelp:
        description: Spawn a book that describes the server.
     rankup:
        description: Rankup to the next level if you're still within the prison!
     donate:
        description: View the link to donate to our server!
     claimdonator:
        description: Claim the donator rank if you haven't already.
     points:
        description: View your donation point count.
     donatorpoints:
        description: View your donation point count.
     solitary:
        description: Add or remove a player from solitary confinement.
     solitarylist:
        description: View all players in solitary.
     spawn:
        description: Go to spawn based on your rank.
     setspawn:
        description: Set the spawn of a location.
     warp:
        description: Warp to a location.
     now:
        description: The current time based on the server.
     smelt:
        description: Smell all of the ore in your inventory.
     sc:
        description: Shortcut for staffchat
     staffchat:
        description: toggles staffchat or sends one message to staffchat.
